{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: {{ template "promtail.name" . }}
    app: {{ template "promtail.name" . }}
    chart: {{ template "promtail.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "promtail.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}

